version: '3.9'
services:     
  azure-functions:
    image: mcr.microsoft.com/azure-functions/powershell:4.0
    container_name: azure-functions 
    restart: unless-stopped
    ports:
      - "80:80"
    env_file:
      - '.env.azfunc'
    volumes:
      - /home/${USER}/Function Apps:/home/site/wwwroot
